default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Niranjan@psql2026
  host: localhost

development:
  <<: *default
  database: auth_app_development

test:
  <<: *default
  database: auth_app_test

production:
  <<: *default
  database: auth_app_production
  username: auth_app
  password: <%= ENV['AUTH_APP_DATABASE_PASSWORD'] %>